name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean Install Packages
        run: yarn install --force --production
      - name: Deploy Test Server via RSYNC
        id: deploy
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          flags: '-avzr --delete'
          options: ''
          ssh_options: '-p 22'
          src: '/'
          dest: 'root@172.105.122.92:server/'
      - name: Run migrations and server with pm2 config
        uses: appleboy/ssh-action@master
        with:
          host: 172.105.122.92:22
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd server
            NODE_ENV=production npx sequelize db:migrate
            pm2 start ecosystem.config.js --env production
